# _config.yml

# إضافة المجلدات التي لا تريد أن يتم تحويلها أو بناؤها.
exclude:
  - docs/assets/css/style.scss
  - docs/_site
  - .jekyll-cache

# إذا كان لديك إعدادات إضافية لتكوين Jekyll هنا، يمكنك إضافتها
title: "Roblox Friend Remover"
description: "A tool to mass remove friends from Roblox."
theme: jekyll-theme-primer
